### ISSUE TITLE
Clean UP & Dockerization eos7jlv

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7jlv#1]

**Comment by GemmaTuron** [comment]
@HellenNamulinda 

I have updated the workflows on this model

**Comment by HellenNamulinda** [comment]
I have pushed the changes and created a [PR](https://github.com/ersilia-os/eos7jlv/pull/3)

The model makes predictions online and returns 100 nearest neighbors of a given molecule, according to ECFP4 Tanimoto similarity, in the GDBMedChem database.  
There are some smiles that the model can't handle. Forexample [N#Cc4ccc(c2nnc3cccc(C(=O)Nc1ccnc(C(F)(F)F)c1)n23)cc4 ](https://gdb-medchem-simsearch.gdb.tools/search?smi=N#Cc4ccc(c2nnc3cccc(C(=O)Nc1ccnc(C(F)(F)F)c1)n23)cc4&fp=ECfp4&db=GDBMedChem&nnc=100), both within ersilia served model run api and run.sh 

CLI fetch: [eos7jlv_repo_fetch_updated.log](https://github.com/ersilia-os/eos7jlv/files/12228796/eos7jlv_repo_fetch_updated.log)
Test file: [test.csv](https://github.com/ersilia-os/eos7jlv/files/12228807/test.csv)
CLI Output: [eos7jlv_cli_output.csv](https://github.com/ersilia-os/eos7jlv/files/12228795/eos7jlv_cli_output.csv)
Run.sh: [7jlv_run_output.csv](https://github.com/ersilia-os/eos7jlv/files/12228798/7jlv_run_output.csv)

**Comment by GemmaTuron** [comment]
Thanks @HellenNamulinda 

Just to be sure, could you double check that molecules that cannot be calculated also fail in the server?

**Comment by HellenNamulinda** [comment]
@Gemma,
Yes, I checked and provided the link to the server error. `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
See [N#Cc4ccc(c2nnc3cccc(C(=O)Nc1ccnc(C(F)(F)F)c1)n23)cc4 ](https://gdb-medchem-simsearch.gdb.tools/search?smi=N#Cc4ccc(c2nnc3cccc(C(=O)Nc1ccnc(C(F)

**Comment by GemmaTuron** [comment]
@HellenNamulinda 

Could you open a PR to modify the name of the script to main.py and change it in the run.sh as well?
Thanks!
